### ISSUE TITLE
Issue in Environment variables setup

### ISSUE THREAD

**Issue by AtlasPilotPuppy** [dzuqe/npc#1]
I created the test net and started it.
checked the status using `goal status` and `make status`
All looks good.
The 
wallet gets created under 
`~/algorand/algo-builder/infrastructure/node_data/Primary` Not `PrimaryNode` like the example says

But when i deploy i get the following error 
```
➜  npc make deploy
goal app create --creator IFM4HAAKD3Z7GAOKWQ4SZILY6AMOKHDSW6RWR4MS7MPIC25F4V2E2XDBDE \
                --approval-prog ./build/george_interact.teal \
    --clear-prog ./build/clear_state.teal \
                --local-byteslices 0 \
                --local-ints 0 \
                --global-byteslices 1 \
                --global-ints 1 -d "~/algorand/algo-builder/infrastructure/node_data"
No wallets found. Create a new wallet with `goal wallet new [wallet name]` 
```
The wallets exist under the `Primary` Directory
which i tried adding to the path and it complained about not finding algod. 
Since this is a beginer example this needs to be fixed and made easy to implement.

**Comment by dzuqe** [comment]
hey @anantasty , thanks for taking a look at my tutorial! It appears that you're using the incorrect node sandbox path. The correct path is `~/algorand/algo-builder/infrastructure/node_data/PrimaryNode`. I should've added an example of this path in the tut.

**Comment by AtlasPilotPuppy** [comment]
That's exactly what I needed. Thanks
